apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "optimize-live.fullname" . }}
  labels:
    {{- include "optimize-live.labels" . | nindent 4 }}
  namespace: {{ include "optimize-live.namespace" . }}
data:
  STORMFORGE_AUTHORIZATION_CLIENT_ID: {{ .Values.authorization.clientID | b64enc }}
  STORMFORGE_AUTHORIZATION_CLIENT_SECRET: {{ .Values.authorization.clientSecret | b64enc }}
  STORMFORGE_SERVER_IDENTIFIER: {{ .Values.authorization.serverIdentifier | b64enc }}
  STORMFORGE_SERVER_ISSUER: {{ .Values.authorization.serverIssuer | b64enc }}
  STORMFORGE_TOKEN_ENDPOINT: {{ .Values.authorization.tokenEndpoint | b64enc }}
