# Default values for optimize-live.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

component:
  image:
    controller:
      repository: registry.stormforge.io/optimize-live/controller
      pullPolicy: IfNotPresent
      tag: 0.0.11
    tsdb:
      repository: registry.stormforge.io/optimize-live/tsdb
      pullPolicy: IfNotPresent
      tag: 0.0.5
    applier:
      repository: registry.stormforge.io/optimize-live/applier
      pullPolicy: IfNotPresent
      tag: 0.0.4
    recommender:
      repository: registry.stormforge.io/optimize-live/recommender
      pullPolicy: IfNotPresent
      tag: 0.1.1
    grafana:
      repository: grafana/grafana-oss
      pullPolicy: IfNotPresent
      tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
defaultNamespace: stormforge-system

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

rbac:
  clusterRole:
    create: true
    name: ""
  clusterRoleBinding:
    create: true
    name: ""

imageCredentials:
  registry: registry.stormforge.io
  username: username
  password: password

stormforge:
  address: https://api.stormforge.io/

authorization:
  issuer: https://api.stormforge.io/
  clientID: id
  clientSecret: secret

metricsURL: http://prometheus:9090

podAnnotations: {}

podSecurityContext: {}

securityContext:
  runAsNonRoot: true

extraEnvVars: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 500m
  #   memory: 128Mi
  # requests:
  #   cpu: 10m
  #   memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /readyz
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10
