apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: optimize
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    control-plane: controller-manager
    helm.sh/chart: '{{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_"
      | trunc 63 | trimSuffix "-" }}'
  name: '{{ .Release.Name }}-controller-manager'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/name: optimize
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        stormforge.io/secretHash: '{{ include (print $.Template.BasePath "/secret.yaml")
          . | sha256sum }}'
      labels:
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/name: optimize
        app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
        control-plane: controller-manager
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: '{{ .Release.Name }}-manager'
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion
          }}'
        imagePullPolicy: '{{ .Values.image.pullPolicy }}'
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 250Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      terminationGracePeriodSeconds: 10
