apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: optimize
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    control-plane: controller-manager
    helm.sh/chart: '{{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/name: optimize
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/name: optimize
        app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
        control-plane: controller-manager
      annotations:
        stormforge.io/secretHash: '{{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}'
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: manager
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}'
        envFrom:
        - secretRef:
            name: '{{ .Release.Name }}-manager'
        env:
        - name: DEFAULT_SETUP_IMAGE
          value: '{{ .Values.setupTasks.image.repository }}:{{ .Values.setupTasks.image.tag | default .Chart.AppVersion }}'
        - name: OPTIMIZE_TRIALS_STORMFORGE_PERF_IMAGE
          value: '{{ .Values.trialJobs.perftest.image.repository }}:{{ .Values.trialJobs.perftest.image.tag }}'
        - name: OPTIMIZE_TRIALS_LOCUST_IMAGE
          value: '{{ .Values.trialJobs.locust.image.repository }}:{{ .Values.trialJobs.locust.image.tag }}'
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 250Mi
        imagePullPolicy: '{{ .Values.image.pullPolicy }}'
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
