{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ .Release.Name }}-manager-role'
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: optimize
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}'
rules:
- resources:
  - namespaces
  apiGroups:
  - ""
  verbs:
  - list
- resources:
  - pods
  apiGroups:
  - ""
  verbs:
  - list
- resources:
  - jobs
  apiGroups:
  - batch
  - extensions
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- resources:
  - experiments
  apiGroups:
  - optimize.stormforge.io
  verbs:
  - get
  - list
  - update
  - watch
- resources:
  - experiments
  - experiments/finalizers
  apiGroups:
  - optimize.stormforge.io
  verbs:
  - get
  - list
  - update
  - watch
- resources:
  - trials
  apiGroups:
  - optimize.stormforge.io
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- resources:
  - trials
  - trials/finalizers
  apiGroups:
  - optimize.stormforge.io
  verbs:
  - get
  - list
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ .Release.Name }}-manager-rolebinding'
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: optimize
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}'
roleRef:
  name: '{{ .Release.Name }}-manager-role'
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: default
  namespace: '{{ .Release.Namespace }}'
  kind: ServiceAccount
{{- if .Values.rbac.bootstrapPermissions }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ .Release.Name }}-patching-role'
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: optimize
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}'
rules:
- resources:
  - configmaps
  apiGroups:
  - ""
  verbs:
  - get
  - patch
- resources:
  - deployments
  - statefulsets
  apiGroups:
  - apps
  - extensions
  verbs:
  - get
  - patch
- resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
- resources:
  - pods
  apiGroups:
  - ""
  verbs:
  - list
  - watch
- resources:
  - clusterroles
  - clusterrolebindings
  apiGroups:
  - rbac.authorization.k8s.io
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- resources:
  - serviceaccounts
  - configmaps
  - secrets
  - services
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- resources:
  - deployments
  - statefulsets
  apiGroups:
  - apps
  - extensions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- resources:
  - experiments
  apiGroups:
  - optimize.stormforge.io
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ .Release.Name }}-patching-rolebinding'
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: optimize
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}'
roleRef:
  name: '{{ .Release.Name }}-patching-role'
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: default
  namespace: '{{ .Release.Namespace }}'
  kind: ServiceAccount
{{- end -}}
{{- end -}}
