apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Release.Name }}-manager'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: optimize
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}'
type: Opaque
data:
  STORMFORGE_AUTHORIZATION_CLIENT_ID: '{{ .Values.authorization.clientID | b64enc }}'
  STORMFORGE_AUTHORIZATION_CLIENT_SECRET: '{{ .Values.authorization.clientSecret | b64enc }}'
  STORMFORGE_SERVER_IDENTIFIER: '{{ .Values.stormforge.address | b64enc }}'
  STORMFORGE_SERVER_ISSUER: '{{ .Values.authorization.issuer | b64enc }}'
  {{- if .Values.datadog.apiKey }}
  DATADOG_API_KEY: '{{ .Values.datadog.apiKey | b64enc }}'
  {{- end }}
  {{- if .Values.datadog.appKey }}
  DATADOG_APP_KEY: '{{ .Values.datadog.appKey | b64enc }}'
  {{- end }}
  {{- if and .Values.newrelic.accountID .Values.newrelic.userKey }}
  NEW_RELIC_ACCOUNT_ID: '{{ .Values.newrelic.accountID | b64enc }}'
  NEW_RELIC_API_KEY: '{{ .Values.newrelic.userKey | b64enc }}'
  {{- end }}
  {{- range .Values.extraEnvVars }}
  {{ .name }}: '{{ .value | b64enc }}'
  {{- end }}
