apiVersion: v1
data:
  STORMFORGE_AUTHORIZATION_CLIENT_ID: '{{ .Values.authorization.clientID | b64enc
    }}'
  STORMFORGE_AUTHORIZATION_CLIENT_SECRET: '{{ .Values.authorization.clientSecret |
    b64enc }}'
  STORMFORGE_SERVER_IDENTIFIER: '{{ .Values.stormforge.address | b64enc }}'
  STORMFORGE_SERVER_ISSUER: '{{ .Values.authorization.issuer | b64enc }}'
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_"
      | trunc 63 | trimSuffix "-" }}'
  name: '{{ .Release.Name }}-manager'
  namespace: '{{ .Release.Namespace }}'
type: Opaque
