image:
  repository: thestormforge/optimize-controller
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
rbac:
  create: true
  bootstrapPermissions: true
stormforge:
  address: https://api.stormforge.io/
authorization:
  issuer: https://api.stormforge.io/
  clientID: ""
  clientSecret: ""
datadog:
  apiKey:  # <DATADOG_API_KEY>
  appKey:  # <DATADOG_APP_KEY>
newrelic:
  accountID:  # <NEW_RELIC_ACCOUNT_ID>
  userKey:  # <NEW_RELIC_API_KEY>
extraEnvVars: []
# - name: FOO
#   value: bar
setupTasks:
  image:
    repository: thestormforge/setuptools
    # Default is the chart appVersion.
    tag: ""
trialJobs:
  perftest:
    image:
      repository: thestormforge/optimize-trials
      tag: v0.0.3-stormforge-perf
  locust:
    image:
      repository: thestormforge/optimize-trials
      tag: v0.0.3-locust
