name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Need to use a PAT so this will trigger the release action
          token: ${{ secrets.BMASTERS_TOKEN }}
      - name: Build Chart
        env:
          GIT_COMMITTER_NAME: Butch Masters
          GIT_COMMITTER_EMAIL: b-masters@users.noreply.github.com
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
        run: |-
          if git commit -aF <(./build.sh) ; then
            git push
          else
            echo "::warning title=No changes::There were no changes made by this build."
          fi
